name: Build Eleventy and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy
        run: npm run build

      - name: Copy _site to root
        run: |
          cp -r _site/* _site
      
      - name: Commit built site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Rebuild site [skip ci]" || echo "No changes to commit"
          git push
