name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches: ["main"]  # source branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          cp -r _site/* _site
      
      - name: Commit built site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Rebuild site [skip ci]" || echo "No changes to commit"
          git push


